### ISSUE TITLE
关于New Tab的收藏夹

### ISSUE THREAD

**Issue by hiNISAL** [awesomes-cn/fercard#1]
新的选项卡中是否可以加入收藏夹相关的元素
之前没有插件的时候 顶部是有收藏夹的
谢谢

**Comment by bimohxh** [comment]
不是太明白你的意思，能描述清楚一点吗

**Comment by hiNISAL** [comment]
chrome默认的新标签 顶上有收藏夹
当使用了fercard之后 收藏夹是不显示的 应该是以页面代替原来的标签页的原因吧
【当然如果在设置里设置了“显示书签栏”不会有这个问题】
这个问题可以解决吗 我不了解chrome插件的开发
谢谢

**Comment by bimohxh** [comment]
额，发现你说的情况了，看了几个其它的新标签页插件，也是一样的效果，估计自定义是只能这样的，可以手动勾选显示书签栏

**Comment by hiNISAL** [comment]
嗯 不过没什么大碍 谢谢哦
